version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: ralph

archives:
  - formats: [binary]
    name_template: "ralph-{{ .Os }}-{{ .Arch }}"

release:
  github:
    owner: scripness
    name: ralph

changelog:
  use: github-native
